version: '3.8'

services:
  db:
    image: mariadb:11
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: petagenda
      MYSQL_USER: petuser
      MYSQL_PASSWORD: petpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./privileges.sql:/docker-entrypoint-initdb.d/privileges.sql
      - ./backend/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: mysql://petuser:petpassword@db:3306/petagenda
      JWT_SECRET: pet-agenda-secret-key
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - '3001:3001'
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    depends_on:
      - backend

volumes:
  db_data:
